---
title: "Find Nome"
output: pdf_document
---

```{r desc, include = FALSE}
# PURPOSE
# The purpose of this script is to display Nome, AK in both the ERA5 grid and the grid used in the WRF downscaling efforts. 
```

# ERA5

Nome in the ERA5 grid

```{r setup, echo = FALSE}
knitr::opts_knit(echo = FALSE)

# plot mask as rectangles
plot_mask <- function(mask_df, res = 2e4) {
  plot(mask_df[, 1:2], xlab = "Lon", ylab = "Lat")

  hres <- res/2
  rect_df <- data.frame(
    xleft = mask_df[, 1] - hres, 
    xright = mask_df[, 1] + hres,
    ybottom = mask_df[, 2] - hres, 
    ytop = mask_df[, 2] + hres
  )
  
  mask_cols <- c("#3399FF", "#669900")
  rect(
    rect_df$xleft, rect_df$ybottom, 
    rect_df$xright, rect_df$ytop,
    col = mask_cols[mask_df$mask + 1]
  )
  
  points(mask_df[, 1:2], pch = 19)
}
  
library(ncdf4)
library(knitr)
library(snaptools)

# extract lon and lat from nc file and close
era_lsm_path <- "../data-raw/ERA5/ERA5_land_sea_mask_Nome_sector.nc"
era_lsm_nc <- nc_open(era_lsm_path)
era_lon <- ncvar_get(era_lsm_nc, varid = "longitude")
era_lat <- ncvar_get(era_lsm_nc, varid = "latitude")
era_lsm <- ncvar_get(era_lsm_nc, varid = "lsm")
nc_close(lsm_nc)

Nlon <- -165.406387
Nlat <- 64.501114
Nome_coords <- data.frame(x = Nlon, y = Nlat)
Nome_coords_era <- Nome_coords
Nome_coords_era[, 1] <- 360 - Nome_coords_era[, 1] * (-1)

```

Nome coordinates: `r paste0("Lon: ", Nlon, "; Lat: ", Nlat, " (lon used in ERA5: ", Nome_coords_era[1], ")")`

```{r era5_grid, echo = FALSE}
# plot grid and Nome
era_coords <- expand.grid(lon, lat)
era_mask_df <- make_mask_df(coords)
era_mask_df$mask <- round(as.vector(lsm))

plot_mask(era_mask_df, res = 0.5)
points(Nome_coords_era, col = "red", pch = 19)

# save extent values of the 9 cells around Nome 
xd <- Nome_coords_era$x[1] - era_lon 
yd <- Nome_coords_era$y[1] - era_lat
# west extent index
wei <- which(xd == min(xd[which(xd > 0)])) - 1
# east extent index
eei <- wei + 2
# south extent index
sei <- which(yd == min(abs(yd))) + 1
# North extent index
nei <- sei - 2

bb <- data.frame(value = c(era_lat[nei], era_lon[wei], era_lat[sei], era_lon[eei]),
                 extent = c("north", "west", "south", "east"))
write.csv(bb, "data/era5_Nome_bb.csv")

```

The bounds for the nine ERA5 cells around Nome (N and S and the two adjacent inland (E)) are: `r kable(bb)` and are saved as **era5_Nome_bb.csv**  

# WRF

Nome in the WRF grid

```{r wrf_grid, echo = FALSE}
# get wrf mask coordinates surrounding Nome
mask_df <- wrf_xy(Nome_coords, ret_mask = TRUE)
# transform Nome coords to WRF proj
Nome_coords_wrf <- wrf_transform(Nome_coords)

plot_mask(mask_df)
points(Nome_coords_wrf, col = "red", pch = 19)

```
